# Generated by Django 5.0.6 on 2024-12-02 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='passport_size_photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='SSOID',
            field=models.CharField(default='defaultSSOID', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='merchantId',
            field=models.CharField(default='defaultMerchantId', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
