# Generated by Django 5.0.6 on 2024-12-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_passport_size_photo_profile_ssoid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
