# Generated by Django 5.0.6 on 2024-12-02 22:08

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_size_photo', models.ImageField(upload_to=user.models.custom_image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssoid', models.CharField(default='defaultSSOID', max_length=100)),
                ('merchantid', models.CharField(default='defaultMerchantId', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='InfoAPI',
        ),
    ]
