# Generated by Django 5.1 on 2024-09-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantID', models.CharField(max_length=50)),
                ('SSOID', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
