# Generated by Django 5.0.6 on 2024-12-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_profile_details_delete_infoapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_details',
            name='merchantid',
        ),
        migrations.RemoveField(
            model_name='profile_details',
            name='ssoid',
        ),
        migrations.AddField(
            model_name='profile_details',
            name='merchantId',
            field=models.CharField(default='defaultMerchantId', max_length=50),
        ),
        migrations.AddField(
            model_name='profile_details',
            name='SSOID',
            field=models.CharField(default='defaultSSOID', max_length=50),
        ),
    ]
