# Generated by Django 5.0.6 on 2024-12-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_infoapi_remove_profile_details_ssoid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Profile_details',
        ),
    ]
