# Generated by Django 5.0.6 on 2024-12-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_infoapi_emali_remove_infoapi_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDF_file', models.FileField(upload_to='UserFormPDF/FormOutputPDF/')),
            ],
        ),
    ]
