# Generated by Django 5.0.6 on 2024-12-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_pdf_file_userform_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='file',
        ),
        migrations.AddField(
            model_name='userform',
            name='file_path',
            field=models.URLField(default=123),
            preserve_default=False,
        ),
    ]
