# Generated by Django 5.0.6 on 2024-12-04 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_userform_file_userform_file_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userform',
            options={'verbose_name': 'User Form', 'verbose_name_plural': 'User Forms'},
        ),
        migrations.RemoveField(
            model_name='userform',
            name='file_path',
        ),
        migrations.AddField(
            model_name='userform',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='disability_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userform',
            name='disability_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='division_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='father_name',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userform',
            name='full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userform',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='graduate_passing_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='graduate_passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='higher_secondary_passing_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='higher_secondary_passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='i_agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userform',
            name='id_proof_marks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='id_proof_school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='id_proof_select',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='id_proof_study_center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='marital_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='mother_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userform',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='passport_size_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/'),
        ),
        migrations.AddField(
            model_name='userform',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='post_graduate_passing_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='post_graduate_passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='professional_passing_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='professional_passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='secondary_passing_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='secondary_passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.location'),
        ),
    ]
