# Generated by Django 5.0.6 on 2024-12-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_userform_options_remove_userform_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
