# Generated by Django 5.0.6 on 2024-12-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_userform_father_name_alter_userform_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
