# Generated by Django 5.0.6 on 2024-12-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_userform_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='dsrvs_status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
