# Generated by Django 5.0.6 on 2024-12-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_userform_dsrvs_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
