# Generated by Django 5.0.6 on 2024-12-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_delete_userform'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('fullName', models.CharField(max_length=100)),
                ('fatherName', models.CharField(max_length=100)),
                ('motherName', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('marital', models.CharField(max_length=100)),
                ('disability', models.CharField(max_length=100)),
                ('select_disability', models.CharField(max_length=100)),
                ('dsrvs', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('userstate', models.CharField(max_length=100)),
                ('userdistrict', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('passing_year', models.CharField(max_length=100)),
                ('diviosn_grade', models.CharField(max_length=100)),
                ('secondary_passing_year', models.CharField(max_length=100)),
                ('secondary_passing_grade', models.CharField(max_length=100)),
                ('higher_secondary_passing_year', models.CharField(max_length=100)),
                ('higher_secondary_passing_grade', models.CharField(max_length=100)),
                ('graduate_passing_year', models.CharField(max_length=100)),
                ('graduate_passing_grade', models.CharField(max_length=100)),
                ('post_graduate_passing_year', models.CharField(max_length=100)),
                ('post_graduate_passing_grade', models.CharField(max_length=100)),
                ('professional_passing_year', models.CharField(max_length=100)),
                ('professional_passing_grade', models.CharField(max_length=100)),
                ('id_proof_select', models.CharField(max_length=100)),
                ('id_proof_number', models.CharField(max_length=100)),
                ('id_proof_marks', models.CharField(max_length=100)),
                ('id_proof_study_center', models.CharField(max_length=100)),
                ('id_proof_school', models.CharField(max_length=100)),
                ('i_agree', models.CharField(max_length=100)),
                ('passport_size_photo', models.CharField(max_length=100)),
            ],
        ),
    ]
