# Generated by Django 5.0.6 on 2024-12-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_userform_passport_size_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoAPI',
        ),
    ]
