# Generated by Django 5.0.6 on 2024-12-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_delete_infoapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssoid', models.CharField(max_length=30)),
                ('merchantid', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
