# Generated by Django 5.0.6 on 2024-12-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
