# Generated by Django 5.0.6 on 2024-12-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='passport_size_photo',
            field=models.ImageField(blank=True, null=True, upload_to='UserFormPDF/userform/'),
        ),
    ]
