# Generated by Django 5.0.6 on 2024-12-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_userform_passport_size_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='userform/'),
        ),
    ]
