# Generated by Django 5.0.6 on 2024-12-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_userform_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='captcha_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='dated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
